In [126]:
import pandas as pd

df_x=pd.read_csv("/home/abhay/Desktop/Files/machine_learning_challenge/beginner/data/trainnew.csv")
df_y=pd.read_csv("/home/abhay/Desktop/Files/machine_learning_challenge/beginner/data/train_y.csv")
test_x=pd.read_csv("/home/abhay/Desktop/Files/machine_learning_challenge/beginner/data/testnew.csv")

In [127]:
import numpy as np
from numpy.linalg import inv
print(np.shape(df_x))
print(np.shape(df_y))
print(np.shape(test_x))

(344, 11)
(344, 1)
(255, 11)

In [128]:
x_trans=df_x.transpose()
a=np.matmul(x_trans,df_x)
b=inv(a)
c=np.matmul(b,x_trans)
d=np.matmul(c,df_y)
print(np.shape(d))

(11, 1)

In [154]:
y_test=np.zeros((255,1))
y_test=np.matrix(y_test)
print(np.shape(y_test))
x=np.matrix(test_x)
i=0
for i in range(0,255):
    x_test=x[i,]
    x_test=np.matrix(x_test)
    predict=np.matmul(x_test,d)
    y=np.abs(predict)
    y_test[i]=np.round(y)
#print(y_test)
np.savetxt('text.csv', y_test, delimiter=',')
#np.to_csv("text.csv")

(255, 1)

In [118]:
#testing percentage
#actual=np.matrix(df_y)
#actual=actual[3]
#print(actual)
#print(predict)
#accu=np.divide(np.subtract(actual,predict),actual)
#accu=np.abs(accu)
#print(accu)

In [120]:
test_x

,data_adjust,business_type,avg_age,blue_collar,white_collar,female,male,total_household_size,total_household_income,employee_size,actual _credit_score
0,1,1.0,33.96,22.42,44.74,50.76,49.24,1.58,74121000.0,41.0,95.0
1,1,1.0,37.34,42.41,34.52,50.06,49.94,1.99,45196000.0,4.0,96.0
2,1,1.0,36.06,54.47,33.87,50.46,49.54,2.58,47034000.0,4.0,96.0
3,1,1.0,37.34,42.41,34.52,50.06,49.94,1.99,45196000.0,5.0,89.0
4,1,1.0,33.64,50.70,34.93,51.30,48.70,2.56,45592000.0,5.0,96.0
5,1,1.0,49.47,31.96,38.56,58.01,41.99,1.95,50159000.0,9.0,96.0
6,1,1.0,49.47,31.96,38.56,58.01,41.99,1.95,50159000.0,14.0,81.0
7,1,1.0,39.19,45.27,38.83,50.57,49.43,2.56,51656000.0,3.0,91.0
8,1,1.0,37.75,46.81,23.00,57.80,42.20,2.55,31900000.0,3.0,94.0
9,1,1.0,35.20,72.36,27.18,43.23,56.77,1.80,21388000.0,8.0,96.0
10,1,1.0,35.68,43.19,40.96,49.71,50.29,2.94,57870000.0,5.0,91.0
11,1,1.0,36.24,28.80,40.57,51.25,48.75,2.45,69174000.0,25.0,99.0
12,1,1.0,43.91,19.25,32.92,55.94,44.06,1.91,89723000.0,12.0,98.0
13,1,4.0,37.03,30.36,48.33,54.50,45.50,2.50,71660000.0,10.0,74.0
14,1,1.0,40.82,55.70,29.05,48.85,51.15,2.46,58408000.0,3.0,93.0
15,1,1.0,31.47,44.86,34.58,50.66,49.34,2.35,34902000.0,3.0,94.0
16,1,1.0,37.20,53.02,42.79,53.60,46.40,2.19,37012000.0,15.0,100.0
17,1,1.0,40.22,24.94,44.75,47.99,52.01,2.27,54117000.0,8.0,86.0
18,1,4.0,47.16,45.10,33.23,56.05,43.95,2.14,46371000.0,16.0,89.0
19,1,4.0,37.03,30.36,48.33,54.50,45.50,2.50,71660000.0,35.0,94.0
20,1,1.0,32.44,39.39,39.59,49.56,50.44,3.48,67422000.0,10.0,91.0
21,1,1.0,38.67,34.45,48.78,51.32,48.68,3.21,90372000.0,3.0,81.0
22,1,4.0,32.51,22.11,53.92,51.10,48.90,3.50,96183000.0,15.0,91.0
23,1,1.0,37.87,48.22,30.25,49.75,50.25,2.27,32908000.0,3.0,93.0
24,1,1.0,36.28,35.77,53.65,48.95,51.05,2.25,33824000.0,10.0,86.0
25,1,1.0,28.32,78.80,21.20,49.29,50.71,3.13,34735000.0,15.0,95.0
26,1,1.0,29.59,40.63,27.61,49.96,50.04,2.27,40115000.0,5.0,88.0
27,1,1.0,28.46,39.97,37.61,54.16,45.84,3.32,43828000.0,48.0,98.0
28,1,1.0,48.79,37.43,43.78,54.32,45.68,1.68,36784000.0,15.0,97.0
29,1,1.0,39.89,38.36,40.46,49.26,50.74,2.46,49220000.0,6.0,94.0
...,...,...,...,...,...,...,...,...,...,...,...
314,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN